"""Added Browser column

Revision ID: 4ac20d72e3f9
Revises: 2ff6ca5925c7
Create Date: 2026-07-29 12:03:45.962466

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4ac20d72e3f9'
down_revision = '2ff6ca5925c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Category',
    sa.Column('Category_Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('Category_Id')
    )
    op.create_table('Page',
    sa.Column('Page_Id', sa.Integer(), nullable=False),
    sa.Column('PageName', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('Page_Id')
    )
    op.create_table('Permission',
    sa.Column('Permission_Id', sa.Integer(), nullable=False),
    sa.Column('AddPermission', sa.Boolean(), nullable=False),
    sa.Column('EditPermission', sa.Boolean(), nullable=False),
    sa.Column('DeletePermission', sa.Boolean(), nullable=False),
    sa.Column('ViewPermission', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('Permission_Id')
    )
    op.create_table('Role',
    sa.Column('Role_Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('Role_Id')
    )
    op.create_table('User',
    sa.Column('User_Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Email', sa.String(length=100), nullable=False),
    sa.Column('Password', sa.String(length=100), nullable=False),
    sa.Column('IsVerified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('User_Id')
    )
    op.create_table('EmailOTP',
    sa.Column('OTP_Id', sa.Integer(), nullable=False),
    sa.Column('User_Id', sa.Integer(), nullable=False),
    sa.Column('OTP', sa.String(length=100), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('ExpireyAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['User_Id'], ['User.User_Id'], ),
    sa.PrimaryKeyConstraint('OTP_Id')
    )
    op.create_table('Logs',
    sa.Column('Log_Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('User_Id', sa.Integer(), nullable=True),
    sa.Column('Module', sa.String(length=100), nullable=False),
    sa.Column('Action', sa.String(length=100), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('Method', sa.String(length=10), nullable=True),
    sa.Column('Url', sa.String(length=255), nullable=True),
    sa.Column('IpAddress', sa.String(length=50), nullable=True),
    sa.Column('UserAgent', sa.Text(), nullable=True),
    sa.Column('Status', sa.String(length=20), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['User_Id'], ['User.User_Id'], ),
    sa.PrimaryKeyConstraint('Log_Id')
    )
    op.create_table('Product',
    sa.Column('Product_Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Price', sa.Float(), nullable=False),
    sa.Column('Category_Id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Category_Id'], ['Category.Category_Id'], ),
    sa.PrimaryKeyConstraint('Product_Id')
    )
    op.create_table('RolePermission',
    sa.Column('RolePermission_Id', sa.Integer(), nullable=False),
    sa.Column('Role_Id', sa.Integer(), nullable=False),
    sa.Column('Page_Id', sa.Integer(), nullable=False),
    sa.Column('AddPermission', sa.Boolean(), nullable=False),
    sa.Column('EditPermission', sa.Boolean(), nullable=False),
    sa.Column('DeletePermission', sa.Boolean(), nullable=False),
    sa.Column('ViewPermission', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['Page_Id'], ['Page.Page_Id'], ),
    sa.ForeignKeyConstraint(['Role_Id'], ['Role.Role_Id'], ),
    sa.PrimaryKeyConstraint('RolePermission_Id')
    )
    op.create_table('RoleUser',
    sa.Column('RoleUser_Id', sa.Integer(), nullable=False),
    sa.Column('Role_Id', sa.Integer(), nullable=True),
    sa.Column('User_Id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Role_Id'], ['Role.Role_Id'], ),
    sa.ForeignKeyConstraint(['User_Id'], ['User.User_Id'], ),
    sa.PrimaryKeyConstraint('RoleUser_Id')
    )
    op.drop_table('logs')
    op.drop_table('user')
    op.drop_table('category')
    op.drop_table('permission')
    op.drop_table('role')
    op.drop_table('product')
    op.drop_table('rolepermission')
    op.drop_table('roleuser')
    op.drop_table('page')
    op.drop_table('emailotp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emailotp',
    sa.Column('OTP_Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('User_Id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('OTP', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('CreatedAt', mysql.DATETIME(), nullable=False),
    sa.Column('ExpireyAt', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['User_Id'], ['user.User_Id'], name=op.f('emailotp_ibfk_1')),
    sa.PrimaryKeyConstraint('OTP_Id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('page',
    sa.Column('Page_Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('PageName', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('Page_Id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('roleuser',
    sa.Column('RoleUser_Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('Role_Id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('User_Id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Role_Id'], ['role.Role_Id'], name=op.f('roleuser_ibfk_1')),
    sa.ForeignKeyConstraint(['User_Id'], ['user.User_Id'], name=op.f('roleuser_ibfk_2')),
    sa.PrimaryKeyConstraint('RoleUser_Id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('rolepermission',
    sa.Column('RolePermission_Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('Role_Id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('Page_Id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('AddPermission', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('EditPermission', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('DeletePermission', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('ViewPermission', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Page_Id'], ['page.Page_Id'], name=op.f('rolepermission_ibfk_1')),
    sa.ForeignKeyConstraint(['Role_Id'], ['role.Role_Id'], name=op.f('rolepermission_ibfk_2')),
    sa.PrimaryKeyConstraint('RolePermission_Id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('product',
    sa.Column('Product_Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('Name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('Price', mysql.FLOAT(), nullable=False),
    sa.Column('Category_Id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Category_Id'], ['category.Category_Id'], name=op.f('product_ibfk_1')),
    sa.PrimaryKeyConstraint('Product_Id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('role',
    sa.Column('Role_Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('Name', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('Role_Id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('permission',
    sa.Column('Permission_Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('AddPermission', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('EditPermission', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('DeletePermission', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('ViewPermission', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Permission_Id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('category',
    sa.Column('Category_Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('Name', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('Category_Id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('User_Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('Name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('Email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('Password', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('IsVerified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('User_Id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('logs',
    sa.Column('Log_Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('User_Id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Module', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('Action', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('Description', mysql.TEXT(), nullable=True),
    sa.Column('Method', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('Url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('IpAddress', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('UserAgent', mysql.TEXT(), nullable=True),
    sa.Column('Status', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('CreatedAt', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['User_Id'], ['user.User_Id'], name=op.f('logs_ibfk_1')),
    sa.PrimaryKeyConstraint('Log_Id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('RoleUser')
    op.drop_table('RolePermission')
    op.drop_table('Product')
    op.drop_table('Logs')
    op.drop_table('EmailOTP')
    op.drop_table('User')
    op.drop_table('Role')
    op.drop_table('Permission')
    op.drop_table('Page')
    op.drop_table('Category')
    # ### end Alembic commands ###
