"""init commit for docker

Revision ID: b8784664be97
Revises: 
Create Date: 2026-07-31 11:52:10.297988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8784664be97'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Category',
    sa.Column('Category_Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('Category_Id')
    )
    op.create_table('Page',
    sa.Column('Page_Id', sa.Integer(), nullable=False),
    sa.Column('PageName', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('Page_Id')
    )
    op.create_table('Permission',
    sa.Column('Permission_Id', sa.Integer(), nullable=False),
    sa.Column('AddPermission', sa.Boolean(), nullable=False),
    sa.Column('EditPermission', sa.Boolean(), nullable=False),
    sa.Column('DeletePermission', sa.Boolean(), nullable=False),
    sa.Column('ViewPermission', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('Permission_Id')
    )
    op.create_table('Role',
    sa.Column('Role_Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('Role_Id')
    )
    op.create_table('User',
    sa.Column('User_Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Email', sa.String(length=100), nullable=False),
    sa.Column('Password', sa.String(length=100), nullable=False),
    sa.Column('IsVerified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('User_Id')
    )
    op.create_table('EmailOTP',
    sa.Column('OTP_Id', sa.Integer(), nullable=False),
    sa.Column('User_Id', sa.Integer(), nullable=False),
    sa.Column('OTP', sa.String(length=100), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('ExpireyAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['User_Id'], ['User.User_Id'], ),
    sa.PrimaryKeyConstraint('OTP_Id')
    )
    op.create_table('Logs',
    sa.Column('Log_Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('User_Id', sa.Integer(), nullable=True),
    sa.Column('Module', sa.String(length=100), nullable=False),
    sa.Column('Action', sa.String(length=100), nullable=False),
    sa.Column('Method', sa.String(length=10), nullable=True),
    sa.Column('Url', sa.String(length=255), nullable=True),
    sa.Column('UserAgent', sa.Text(), nullable=True),
    sa.Column('Status', sa.String(length=20), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['User_Id'], ['User.User_Id'], ),
    sa.PrimaryKeyConstraint('Log_Id')
    )
    op.create_table('Product',
    sa.Column('Product_Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Price', sa.Float(), nullable=False),
    sa.Column('Category_Id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Category_Id'], ['Category.Category_Id'], ),
    sa.PrimaryKeyConstraint('Product_Id')
    )
    op.create_table('RolePermission',
    sa.Column('RolePermission_Id', sa.Integer(), nullable=False),
    sa.Column('Role_Id', sa.Integer(), nullable=False),
    sa.Column('Page_Id', sa.Integer(), nullable=False),
    sa.Column('AddPermission', sa.Boolean(), nullable=False),
    sa.Column('EditPermission', sa.Boolean(), nullable=False),
    sa.Column('DeletePermission', sa.Boolean(), nullable=False),
    sa.Column('ViewPermission', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['Page_Id'], ['Page.Page_Id'], ),
    sa.ForeignKeyConstraint(['Role_Id'], ['Role.Role_Id'], ),
    sa.PrimaryKeyConstraint('RolePermission_Id')
    )
    op.create_table('RoleUser',
    sa.Column('RoleUser_Id', sa.Integer(), nullable=False),
    sa.Column('Role_Id', sa.Integer(), nullable=True),
    sa.Column('User_Id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Role_Id'], ['Role.Role_Id'], ),
    sa.ForeignKeyConstraint(['User_Id'], ['User.User_Id'], ),
    sa.PrimaryKeyConstraint('RoleUser_Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RoleUser')
    op.drop_table('RolePermission')
    op.drop_table('Product')
    op.drop_table('Logs')
    op.drop_table('EmailOTP')
    op.drop_table('User')
    op.drop_table('Role')
    op.drop_table('Permission')
    op.drop_table('Page')
    op.drop_table('Category')
    # ### end Alembic commands ###
